# Generated by Django 6.0.5 on 2026-05-29 13:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OkrugTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_okrug', models.CharField(max_length=100, unique=True, verbose_name='Название округа')),
                ('id_chat', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округа',
                'db_table': 'okrug_tab',
            },
        ),
        migrations.CreateModel(
            name='ConfigTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='IMEI')),
                ('addr_orientir', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адресный ориентир')),
                ('lat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Широта')),
                ('long', models.CharField(blank=True, max_length=50, null=True, verbose_name='Долгота')),
                ('autor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор')),
                ('date_records', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('status', models.CharField(choices=[('on', 'Включено'), ('off', 'Выключено')], default='off', max_length=3, verbose_name='Статус')),
                ('okrug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='app_foto_config.okrugtab', verbose_name='Округ')),
            ],
            options={
                'verbose_name': 'Конфигурация фотоловушки',
                'verbose_name_plural': 'Конфигурации фотоловушек',
                'db_table': 'config_tab',
                'ordering': ['-date_records'],
            },
        ),
    ]
